import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve, relative } from 'node:path'
import type { NuxtPage } from '@nuxt/schema'
import type { DomainRouteDocOptions } from './types'

const toPosixPath = (p: string) => p.replace(/\\/g, '/')

/* ------------------------------------------------------------------ */
/*  Flatten helpers                                                     */
/* ------------------------------------------------------------------ */

function flattenPages(
    page: NuxtPage,
    parentFullPath: string
): Array<{ path: string; name: string; file?: string }> {
    const seg = page.path ?? ''
    let fullPath: string
    if (parentFullPath === '') {
        if (seg === '') fullPath = '/'
        else fullPath = seg.startsWith('/') ? seg : `/${seg}`
    } else {
        const base = parentFullPath === '/' ? '' : parentFullPath.replace(/\/$/, '')
        fullPath = seg === '' ? parentFullPath : `${base}/${seg}`.replace(/\/+/g, '/')
    }
    if (fullPath !== '/' && !fullPath.startsWith('/')) fullPath = `/${fullPath}`

    const rows: Array<{ path: string; name: string; file?: string }> = [
        { path: fullPath, name: (page.name as string) || '', file: page.file },
    ]
    for (const child of page.children || []) {
        rows.push(...flattenPages(child, fullPath))
    }
    return rows
}

/* ------------------------------------------------------------------ */
/*  Markdown doc                                                        */
/* ------------------------------------------------------------------ */

function generateMarkdown(
    allRows: Array<{ path: string; name: string; file?: string }>,
    rootDir: string
): string {
    const tableLines = allRows.map((r) => {
        const fp = r.file ? toPosixPath(relative(rootDir, r.file)) : ''
        const safeName = (r.name || '—').replace(/\|/g, '\\|')
        return `| \`${r.path}\` | ${safeName} | \`${fp}\` |`
    })

    return [
        '# Routes (domain-pages)',
        '',
        '_Fichier généré automatiquement par le module `domain-pages` — ne pas modifier à la main._',
        '',
        '| Chemin | Nom | Fichier source |',
        '| --- | --- | --- |',
        ...tableLines,
        '',
        `**Total :** ${allRows.length} route(s).`,
        '',
    ].join('\n')
}

/* ------------------------------------------------------------------ */
/*  JSON route map                                                      */
/* ------------------------------------------------------------------ */

function generateRouteMapJson(
    allRows: Array<{ path: string; name: string; file?: string }>
): string {
    const entries = allRows.map((r) => ({
        path: r.path,
        name: r.name,
        file: r.file ? toPosixPath(r.file) : undefined,
    }))
    return JSON.stringify(entries, null, 2) + '\n'
}

/* ------------------------------------------------------------------ */
/*  Typed route names (typed-router.d.ts)                              */
/* ------------------------------------------------------------------ */

function generateTypedRoutes(
    allRouteNames: Array<{ path: string; name: string }>
): string {
    const uniqueNames = [...new Set(allRouteNames.map((r) => r.name).filter(Boolean))]
    uniqueNames.sort()

    const unionMembers = uniqueNames.map((n) => `  | '${n}'`).join('\n')

    return [
        '// This file is auto-generated by the domain-pages module. Do not edit manually.',
        '',
        "declare module 'vue-router' {",
        '  interface TypedRouteRecord {',
        '    name: DomainPagesRouteName',
        '  }',
        '  interface TypedRouteLocationRaw {',
        '    name?: DomainPagesRouteName',
        '  }',
        '}',
        '',
        'type DomainPagesRouteName =',
        unionMembers || '  | never',
        '',
    ].join('\n')
}

/* ------------------------------------------------------------------ */
/*  Public entry point                                                  */
/* ------------------------------------------------------------------ */

export interface RouteDocContext {
    rootDir: string
    routeDoc: { enabled: boolean; outDir: string; fileName: string }
    routeMap: Map<string, NuxtPage>
    allRouteNames: Array<{ path: string; name: string }>
    debugLog: (...args: any[]) => void
}

export function writeRouteDoc(ctx: RouteDocContext): void {
    const { rootDir, routeDoc, routeMap, allRouteNames, debugLog } = ctx

    if (!routeDoc.enabled) return

    // Flatten all routes
    const allRows: Array<{ path: string; name: string; file?: string }> = []
    for (const route of routeMap.values()) {
        allRows.push(...flattenPages(route, ''))
    }
    allRows.sort((a, b) =>
        a.path === b.path
            ? (a.name || '').localeCompare(b.name || '')
            : a.path.localeCompare(b.path)
    )

    const outDirAbs = resolve(rootDir, routeDoc.outDir)
    mkdirSync(outDirAbs, { recursive: true })

    // 1. Markdown doc
    const md = generateMarkdown(allRows, rootDir)
    const outFile = resolve(outDirAbs, routeDoc.fileName)
    writeFileSync(outFile, md, 'utf8')
    debugLog('📝 [domain-pages] route doc écrit:', {
        file: toPosixPath(relative(rootDir, outFile)),
    })

    // 2. JSON route map
    const jsonPath = resolve(outDirAbs, 'route-map.json')
    writeFileSync(jsonPath, generateRouteMapJson(allRows), 'utf8')
    debugLog('📦 [domain-pages] route-map.json écrit:', {
        file: toPosixPath(relative(rootDir, jsonPath)),
    })

    // 3. Typed routes (typed-router.d.ts)
    const typedPath = resolve(outDirAbs, 'typed-router.d.ts')
    writeFileSync(typedPath, generateTypedRoutes(allRouteNames), 'utf8')
    debugLog('🔒 [domain-pages] typed-router.d.ts écrit:', {
        file: toPosixPath(relative(rootDir, typedPath)),
    })
}
