import type { ConflictReport } from '../../shared/runtime/conflicts'
import { isPlainObject } from './merge'

export function collectI18nLeafKeys(
    obj: Record<string, unknown>,
    prefix = ''
): string[] {
    const keys: string[] = []
    for (const [key, value] of Object.entries(obj)) {
        const path = prefix ? `${prefix}.${key}` : key
        if (isPlainObject(value)) {
            keys.push(...collectI18nLeafKeys(value, path))
        } else {
            keys.push(path)
        }
    }
    return keys
}

export function generateTypedI18nDts(keys: string[]): string {
    const unique = [...new Set(keys)].sort()
    const unionMembers = unique.map((k) => `  | '${k.replace(/'/g, "\\'")}'`).join('\n')

    return [
        '// Auto-generated by domain-i18n. Do not edit manually.',
        '',
        'type DomainI18nKey =',
        unionMembers || '  | never',
        '',
        "declare module 'vue-i18n' {",
        '  export interface DefineLocaleMessage {',
        '    [key: DomainI18nKey]: string',
        '  }',
        '}',
        '',
        'export type { DomainI18nKey }',
        '',
    ].join('\n')
}

export interface I18nKeyTracker {
  track(key: string, source: string): ConflictReport | null
}

export function createI18nKeyTracker(): I18nKeyTracker {
  const seen = new Map<string, string>()

  return {
    track(key: string, source: string): ConflictReport | null {
      const prev = seen.get(key)
      if (prev && prev !== source) {
        return {
          kind: 'i18n-key',
          message: `Clé "${key}" écrasée : "${prev}" → "${source}"`,
        }
      }
      if (!prev) seen.set(key, source)
      return null
    },
  }
}

export function reportI18nConflicts(
  reports: ConflictReport[],
  strict: boolean
): void {
  if (reports.length === 0) return
  for (const r of reports) {
    console.warn(`⚠️  [domain-i18n] [${r.kind}] ${r.message}`)
  }
  if (strict) {
    throw new Error(
      `[domain-i18n] ${reports.length} conflit(s) en mode strict — corrigez les clés ou désactivez strict.`
    )
  }
}
